// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0ZF7gC9mJaviuLp6ERbKZ_oC8sUAHm8A',
    appId: '1:403475731321:android:b4382a73eaa9d9d59255a8',
    messagingSenderId: '403475731321',
    projectId: 'life-app-dev',
    storageBucket: 'life-app-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVJzAE_na2l0QId-njdTgeC9sYXMYzs3w',
    appId: '1:403475731321:ios:72c51611b7b619ce9255a8',
    messagingSenderId: '403475731321',
    projectId: 'life-app-dev',
    storageBucket: 'life-app-dev.firebasestorage.app',
    iosBundleId: 'com.ymcompany.lifeapp.dev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVJzAE_na2l0QId-njdTgeC9sYXMYzs3w',
    appId: '1:403475731321:ios:72c51611b7b619ce9255a8',
    messagingSenderId: '403475731321',
    projectId: 'life-app-dev',
    storageBucket: 'life-app-dev.firebasestorage.app',
    iosBundleId: 'com.ymcompany.lifeapp.dev',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_zyfi6ou71x81-fRFeoh8A9z2e2R_erY',
    appId: '1:403475731321:web:72863ffcecc052119255a8',
    messagingSenderId: '403475731321',
    projectId: 'life-app-dev',
    authDomain: 'life-app-dev.firebaseapp.com',
    storageBucket: 'life-app-dev.firebasestorage.app',
    measurementId: 'G-R36PXV9HL6',
  );

}